/* -------------------------------------------------------
   refrigerantDiagram.js – Mitsubishi e-Solution style
   refrigerant piping diagram renderer
   Supports layouts: horizontal-tree, vertical-tree, compact-grid
------------------------------------------------------- */
import { createSvg, g, rect, line, text, path } from './svgUtils.js';
import { drawOutdoorUnit, drawIndoorUnit, drawJoint, drawRemote } from './icons.js';

export function renderRefrigerantDiagram(config, layout) {
    switch (layout) {
        case 'vertical-tree': return renderVerticalTree(config);
        case 'compact-grid': return renderCompactGrid(config);
        default: return renderHorizontalTree(config);
    }
}

/* ==================================================================
   SHARED HELPERS
   ================================================================== */

function drawHeader(svg, x, y, outdoorModel) {
    const hg = g(svg, 'translate(' + x + ',' + y + ')');
    rect(hg, 0, 0, 180, 14, { fill: '#cc0000', stroke: 'none' });
    text(hg, 4, 10, 'HVAC DIAGRAMS', { fontSize: 8, fill: '#fff', fontWeight: '700' });
    text(hg, 60, 10, 'Generated by HVAC Diagram Generator', { fontSize: 6, fill: '#fff' });
    rect(hg, 0, 16, 90, 12, { fill: '#003399', stroke: 'none' });
    text(hg, 4, 25, 'e-solution', { fontSize: 8, fill: '#fff', fontWeight: '600' });
    text(hg, 0, 42, outdoorModel || '', { fontSize: 9, fill: '#333', fontWeight: '600' });
}

function drawProjectInfoBox(svg, x, y, project, n) {
    var ig = g(svg, 'translate(' + x + ',' + y + ')');
    var lines = [
        ['Proyecto', project.name || 'HVAC PROJECT'],
        ['Referencia proy', ''],
        ['Sistema', project.system || 'UE1'],
        ['Condiciones de dise\u00f1o', project.designConditions || ''],
        ['Tirada total de tuber\u00eda', (project.totalPipeLength || 0) + ' m  de  ' + (project.maxPipeLength || 0) + ' m'],
        ['Unidades interiores conectadas totales', String(n)],
        ['Capacidad en fr\u00edo real total', (project.totalCooling || 0) + ' kW / ' + (project.totalHeating || 0) + ' kW'],
        ['Capacidad conectada', project.connectedCapacity || ''],
        ['Factor diversidad', project.diversityFactor || '0%'],
        ['Refrigerante adicional', (project.additionalRefrigerant || 0) + ' kg'],
        ['Cantidad total de refrigerante', (project.totalRefrigerant || 0) + ' kg'],
    ];
    for (var i = 0; i < lines.length; i++) {
        var yy = i * 14;
        text(ig, 0, yy, lines[i][0] + ' : ', { fontSize: 9, fill: '#333' });
        text(ig, 210, yy, lines[i][1], { fontSize: 9, fill: i === 0 ? '#003399' : '#333', fontWeight: i === 0 ? '700' : '400' });
    }
}

/**
 * Flatten a piping tree into an ordered list of nodes for rendering.
 * Each flattened entry has: { unit, gasSize, liquidSize, distance, depth, parentJoint }
 * and the joints/branches info for pipe routing.
 */
function flattenTree(node, depth) {
    if (!node) return [];
    depth = depth || 0;
    if (node.unit) {
        return [{ unit: node.unit, gasSize: node.gasSize || '', liquidSize: node.liquidSize || '', distance: node.distance || 0, depth: depth }];
    }
    if (node.children) {
        var result = [];
        for (var i = 0; i < node.children.length; i++) {
            result = result.concat(flattenTree(node.children[i], depth + 1));
        }
        return result;
    }
    return [];
}

/**
 * Build a list of all branches (joint nodes) from the tree for routing pipes.
 * Returns: [{ joint, gasSize, liquidSize, distance, depth, x, y, childRanges }]
 */
function collectBranches(node, depth) {
    if (!node) return [];
    depth = depth || 0;
    if (node.unit) return [];
    var branches = [];
    if (node.children && node.children.length > 1) {
        var firstCount = countLeaves(node.children[0]);
        branches.push({
            joint: node.joint || '',
            gasSize: node.gasSize || '',
            liquidSize: node.liquidSize || '',
            distance: node.distance || 0,
            depth: depth,
            firstChildLeaves: firstCount,
            totalLeaves: countLeaves(node),
        });
    }
    if (node.children) {
        for (var i = 0; i < node.children.length; i++) {
            branches = branches.concat(collectBranches(node.children[i], depth + 1));
        }
    }
    return branches;
}

function countLeaves(node) {
    if (!node) return 0;
    if (node.unit) return 1;
    if (!node.children) return 0;
    var count = 0;
    for (var i = 0; i < node.children.length; i++) {
        count += countLeaves(node.children[i]);
    }
    return count;
}


/* ==================================================================
   LAYOUT 1: HORIZONTAL TREE (Mitsubishi e-Solution style)
   ================================================================== */

function renderHorizontalTree(config) {
    var units = config.indoor || [];
    var piping = config.piping || {};
    var project = config.project || {};
    var outdoor = config.outdoor || {};
    var n = units.length;

    var ROW_H = 140;
    var MARGIN = 40;
    var TOP = 70;

    var svgW = 1100;
    var svgH = Math.max(600, TOP + n * ROW_H + 80);
    var svg = createSvg(svgW, svgH);
    rect(svg, 0, 0, svgW, svgH, { fill: '#ffffff', stroke: 'none' });

    // Header + project info
    drawHeader(svg, MARGIN, 10, outdoor.model);
    drawProjectInfoBox(svg, svgW - 440, 10, project, n);

    // Outdoor unit
    var ouX = MARGIN, ouY = TOP + 40;
    drawOutdoorUnit(svg, ouX, ouY, outdoor.model);
    text(svg, ouX + 50, ouY + 100, outdoor.model || '', { fontSize: 9, fill: '#003399', anchor: 'middle', fontWeight: '600' });

    // Pipe start point (right of outdoor unit)
    var pipeX = ouX + 103;
    var pipeY = ouY + 35;

    // Flatten tree to get units in order
    var flatUnits = flattenTree(piping, 0);
    if (flatUnits.length === 0) {
        // Fallback: use config.indoor directly
        for (var fi = 0; fi < units.length; fi++) {
            flatUnits.push({ unit: units[fi], gasSize: '3/8"', liquidSize: '1/4"', distance: 5.0, depth: 1 });
        }
    }

    // Collect branch/joint info from the tree
    var branches = collectBranches(piping, 0);

    // Compute unit Y positions
    var unitX = svgW - 250;
    var positions = [];
    for (var i = 0; i < flatUnits.length; i++) {
        positions.push({
            x: unitX,
            y: TOP + 20 + i * ROW_H,
        });
    }

    // Draw pipe routing
    // Main trunk horizontal line
    var trunkGas = piping.gasSize || '5/8"';
    var trunkLiquid = piping.liquidSize || '3/8"';
    var trunkDist = piping.distance || 10;

    // Joint X positions based on depth
    var maxDepth = 0;
    for (var i = 0; i < flatUnits.length; i++) {
        if (flatUnits[i].depth > maxDepth) maxDepth = flatUnits[i].depth;
    }

    var depthSpacing = Math.min(120, (unitX - pipeX - 80) / Math.max(maxDepth + 1, 2));
    var jointXPositions = [];
    for (var d = 0; d <= maxDepth; d++) {
        jointXPositions.push(pipeX + 60 + d * depthSpacing);
    }

    // Draw tree using a recursive walk that places joints and pipes
    var currentUnitIdx = 0;

    function drawNode(node, fromX, fromY, depth) {
        if (!node) return fromY;

        // Leaf node — draw pipe to the unit
        if (node.unit) {
            var ui = currentUnitIdx;
            var uy = positions[ui].y + 25;
            var ux = positions[ui].x;
            var lastJointX = fromX;

            // Horizontal pipe from joint to just before unit
            line(svg, lastJointX, fromY, ux - 10, fromY, { stroke: '#333', strokeWidth: 1.2 });

            // Pipe labels
            var midPipeX = (lastJointX + ux - 10) / 2;
            text(svg, lastJointX + 15, fromY - 8, (node.gasSize || '') + ', ' + (node.liquidSize || ''), { fontSize: 8, fill: '#333' });
            text(svg, lastJointX + 15, fromY + 12, (node.distance || 0) + 'm', { fontSize: 8, fill: '#009900', fontWeight: '500' });

            // Vertical + horizontal to actual unit position if Y differs
            if (Math.abs(fromY - uy) > 3) {
                line(svg, ux - 10, fromY, ux - 10, uy, { stroke: '#333', strokeWidth: 1.2 });
                line(svg, ux - 10, uy, ux, uy, { stroke: '#333', strokeWidth: 1.2 });
            }

            // Draw the indoor unit block
            drawUnitBlockH(svg, ux, positions[ui].y, node.unit);

            // Remote controller
            drawRemote(svg, ux + 195, positions[ui].y + 5, node.unit.remote || 'RC-EX3A');

            currentUnitIdx++;
            return uy;
        }

        // Branch node
        if (node.children && node.children.length > 0) {
            var jx = jointXPositions[Math.min(depth, jointXPositions.length - 1)];

            // Horizontal pipe from entry to joint
            line(svg, fromX, fromY, jx, fromY, { stroke: '#333', strokeWidth: 1.2 });

            // Pipe size labels
            text(svg, fromX + 8, fromY - 8, (node.gasSize || '') + ', ' + (node.liquidSize || ''), { fontSize: 8, fill: '#333' });
            text(svg, fromX + 8, fromY + 12, (node.distance || 0) + 'm', { fontSize: 8, fill: '#009900', fontWeight: '500' });

            // Draw joint
            drawJoint(svg, jx, fromY, node.joint);

            // Process first child at same Y level
            var afterFirst = drawNode(node.children[0], jx + 10, fromY, depth + 1);

            // Process rest of children going downward
            for (var ci = 1; ci < node.children.length; ci++) {
                var nextY = positions[currentUnitIdx].y + 25;
                // Vertical pipe from joint down
                line(svg, jx, fromY, jx, nextY, { stroke: '#333', strokeWidth: 1.2 });
                drawNode(node.children[ci], jx + 10, nextY, depth + 1);
            }

            return afterFirst;
        }

        return fromY;
    }

    drawNode(piping, pipeX, pipeY, 0);

    return svg;
}


/** Draw indoor unit block with all labels for horizontal layout */
function drawUnitBlockH(svg, x, y, unit) {
    var ug = g(svg, 'translate(' + x + ',' + y + ')');

    // Dashed border
    rect(ug, -10, -35, 190, 110, { fill: 'none', stroke: '#999', strokeWidth: 0.6, strokeDash: '4,3' });

    // Capacity (green)
    text(ug, 0, -20, (unit.cooling_kw || 0) + ' kW/' + (unit.heating_kw || 0) + ' kW', { fontSize: 9, fill: '#006600', fontWeight: '600' });

    // Model (blue)
    text(ug, 0, -8, unit.index + '. ' + (unit.model || ''), { fontSize: 8, fill: '#0066cc', fontWeight: '500' });

    // Actual capacity placeholder
    text(ug, 125, -20, '0.00 kW/0.00 kW', { fontSize: 8, fill: '#0066cc' });

    // Indoor unit icon
    drawIndoorUnit(ug, 30, 0, unit.type || 'ducted');

    // Room name
    text(ug, 56, 62, (unit.room || '') + ' ' + (unit.location || ''), { fontSize: 9, fill: '#003399', anchor: 'middle', fontWeight: '600' });

    return ug;
}


/* ==================================================================
   LAYOUT 2: VERTICAL TREE
   ================================================================== */

function renderVerticalTree(config) {
    var units = config.indoor || [];
    var piping = config.piping || {};
    var project = config.project || {};
    var outdoor = config.outdoor || {};
    var n = units.length;
    var COL_W = 210;

    var svgW = Math.max(900, 120 + n * COL_W);
    var svgH = 700;
    var svg = createSvg(svgW, svgH);
    rect(svg, 0, 0, svgW, svgH, { fill: '#ffffff', stroke: 'none' });

    drawHeader(svg, 30, 10, outdoor.model);
    drawProjectInfoBox(svg, svgW - 440, 10, project, n);

    var ouX = svgW / 2 - 50, ouY = 60;
    drawOutdoorUnit(svg, ouX, ouY, outdoor.model);
    text(svg, ouX + 50, ouY + 100, outdoor.model || '', { fontSize: 9, fill: '#003399', anchor: 'middle', fontWeight: '600' });

    var pipeStartX = ouX + 50, pipeStartY = ouY + 90;
    var flatUnits = flattenTree(piping, 0);
    if (flatUnits.length === 0) {
        for (var i = 0; i < units.length; i++) {
            flatUnits.push({ unit: units[i], gasSize: '3/8"', liquidSize: '1/4"', distance: 5.0, depth: 1 });
        }
    }

    var UNIT_Y = svgH - 190;
    var totalW = (flatUnits.length - 1) * COL_W;
    var startX = (svgW - totalW) / 2;

    // Trunk down
    var trunkEndY = ouY + 160;
    line(svg, pipeStartX, pipeStartY, pipeStartX, trunkEndY, { stroke: '#333', strokeWidth: 1.5 });
    text(svg, pipeStartX + 6, pipeStartY + 30, (piping.gasSize || '') + ', ' + (piping.liquidSize || ''), { fontSize: 8, fill: '#333' });
    text(svg, pipeStartX + 6, pipeStartY + 42, (piping.distance || 0) + 'm', { fontSize: 8, fill: '#009900' });

    // Distribution line
    var firstCX = startX + 28;
    var lastCX = startX + (flatUnits.length - 1) * COL_W + 28;
    line(svg, firstCX, trunkEndY, lastCX, trunkEndY, { stroke: '#333', strokeWidth: 1.2 });
    line(svg, pipeStartX, trunkEndY, pipeStartX, trunkEndY, { stroke: '#333', strokeWidth: 1.2 });
    drawJoint(svg, pipeStartX, trunkEndY, piping.joint || '');

    for (var i = 0; i < flatUnits.length; i++) {
        var fu = flatUnits[i];
        var cx = startX + i * COL_W + 28;

        // Drop from distribution to unit
        line(svg, cx, trunkEndY, cx, UNIT_Y, { stroke: '#333', strokeWidth: 1 });
        drawJoint(svg, cx, trunkEndY, '');

        // Pipe label
        text(svg, cx + 5, (trunkEndY + UNIT_Y) / 2, fu.distance + 'm', { fontSize: 8, fill: '#009900' });

        // Unit block
        drawUnitBlockH(svg, cx - 28, UNIT_Y, fu.unit);
        drawRemote(svg, cx - 15, UNIT_Y + 80, fu.unit.remote || 'RC-EX3A');
    }

    return svg;
}


/* ==================================================================
   LAYOUT 3: COMPACT GRID
   ================================================================== */

function renderCompactGrid(config) {
    var units = config.indoor || [];
    var piping = config.piping || {};
    var project = config.project || {};
    var outdoor = config.outdoor || {};
    var n = units.length;
    var COLS = Math.min(n, Math.max(2, Math.ceil(Math.sqrt(n))));
    var ROWS = Math.ceil(n / COLS);
    var CELL_W = 220, CELL_H = 150;

    var gridW = COLS * CELL_W;
    var svgW = Math.max(950, 80 + gridW + 80);
    var svgH = Math.max(600, 230 + ROWS * CELL_H + 40);
    var svg = createSvg(svgW, svgH);
    rect(svg, 0, 0, svgW, svgH, { fill: '#ffffff', stroke: 'none' });

    drawHeader(svg, 30, 10, outdoor.model);
    drawProjectInfoBox(svg, svgW - 440, 10, project, n);

    var ouX = 30, ouY = 60;
    drawOutdoorUnit(svg, ouX, ouY, outdoor.model);
    text(svg, ouX + 50, ouY + 100, outdoor.model || '', { fontSize: 9, fill: '#003399', anchor: 'middle', fontWeight: '600' });

    var trunkY = ouY + 35;
    var gridStartX = 80;
    var gridStartY = ouY + 180;

    // Main trunk
    line(svg, ouX + 103, trunkY, gridStartX + gridW / 2, trunkY, { stroke: '#333', strokeWidth: 1.5 });
    text(svg, ouX + 160, trunkY - 8, (piping.gasSize || '') + ', ' + (piping.liquidSize || ''), { fontSize: 8, fill: '#333' });
    text(svg, ouX + 160, trunkY + 12, (piping.distance || 0) + 'm', { fontSize: 8, fill: '#009900' });

    // Vertical + distribution
    line(svg, gridStartX + gridW / 2, trunkY, gridStartX + gridW / 2, gridStartY - 20, { stroke: '#333', strokeWidth: 1.5 });
    line(svg, gridStartX, gridStartY - 20, gridStartX + gridW, gridStartY - 20, { stroke: '#333', strokeWidth: 1.2 });

    var flatUnits = flattenTree(piping, 0);
    if (flatUnits.length === 0) {
        for (var i = 0; i < units.length; i++) {
            flatUnits.push({ unit: units[i], gasSize: '3/8"', liquidSize: '1/4"', distance: 5.0, depth: 1 });
        }
    }

    for (var i = 0; i < flatUnits.length; i++) {
        var fu = flatUnits[i];
        var u = fu.unit;
        var col = i % COLS, row = Math.floor(i / COLS);
        var cx = gridStartX + col * CELL_W + CELL_W / 2;
        var uy = gridStartY + row * CELL_H;

        line(svg, cx, gridStartY - 20, cx, uy - 10, { stroke: '#333', strokeWidth: 1 });
        drawJoint(svg, cx, gridStartY - 20, '');

        var ug = g(svg, 'translate(' + (cx - 28) + ',' + uy + ')');
        drawIndoorUnit(ug, 0, 0, u.type || 'ducted');
        text(ug, 28, -10, (u.cooling_kw || 0) + '/' + (u.heating_kw || 0) + ' kW', { fontSize: 8, fill: '#006600', anchor: 'middle', fontWeight: '600' });
        text(ug, 28, 60, u.index + '. ' + (u.model || ''), { fontSize: 7, fill: '#333', anchor: 'middle' });
        text(ug, 28, 72, u.room || '', { fontSize: 8, fill: '#003399', anchor: 'middle', fontWeight: '600' });
    }

    return svg;
}
